name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    tags:
      - "v*"
  pull_request:
    branches: [ "master" ]
    tags:
      - "v*"

env:
  IMAGE_TAG: ${{ contains(github.ref, 'refs/tags/') && github.ref_name || github.sha }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  
jobs:
  account-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file account-service/Dockerfile --tag devynchou/simplife.account.service:${{ env.IMAGE_TAG }}
    - name: Echo Docker image tag
      run: echo ${{env.IMAGE_NAME}}
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}
    - name: push Docker image to Docker Hub
      run: docker push devynchou/simplife.account.service:${{ env.IMAGE_TAG }}
      
  ledger-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file ledger-service/Dockerfile --tag devynchou/simplife.ledger.service:${{ env.IMAGE_TAG }}
    - name: Echo Docker image tag
      run: echo ${{env.IMAGE_NAME}}
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}
    - name: push Docker image to Docker Hub
      run: docker push devynchou/simplife.ledger.service:${{ env.IMAGE_TAG }}

  agenda-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file agenda-service/Dockerfile --tag devynchou/simplife.agenda.service:${{ env.IMAGE_TAG }}
    - name: Echo Docker image tag
      run: echo ${{env.IMAGE_NAME}}
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}
    - name: push Docker image to Docker Hub
      run: docker push devynchou/simplife.agenda.service:${{ env.IMAGE_TAG }}
