name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  tags:
    - 'v*

env:
  IMAGE_TAG: ${{ github.event_name=="tags" && ${GITHUB_REF##*/} || github.sha }}
  DOCKERHUB_USERNAME: devynchou
  DOCKERHUB_TOKEN: dckr_pat_dQJ8GiIOtj020SL6t3SmNNc69T0
  
jobs:
  account-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file account-service/Dockerfile --tag devynchou/simplife.account.service:${{ env.IMAGE_TAG }}
    - name: Echo Docker image tag
      run: echo ${{env.IMAGE_NAME}}
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}
    - name: push Docker image to Docker Hub
      run: docker push devynchou/simplife.account.service:${{ env.IMAGE_TAG }}
      
  ledger-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file ledger-service/Dockerfile --tag devynchou/simplife.ledger.service:${{ env.IMAGE_TAG }}
    - name: Echo Docker image tag
      run: echo ${{env.IMAGE_NAME}}
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}
    - name: push Docker image to Docker Hub
      run: docker push devynchou/simplife.ledger.service:${{ env.IMAGE_TAG }}
    
